<?php

declare(strict_types=1);

namespace Kanopi\Crs\Refresh;

use Kanopi\Crs\Parser\ParsedRule;

/**
 * Writes parsed CRS rules to the engine's on-disk cache:
 *   rules/manifest.json       — version + file index
 *   rules/<source>.json       — per-source-file rule array (review-friendly)
 *   rules/compiled.php        — single var_export'd array (runtime hot path)
 */
final class RuleWriter
{
    public function __construct(private readonly string $rulesDir)
    {
        if (!is_dir($rulesDir) && !mkdir($rulesDir, 0755, true) && !is_dir($rulesDir)) {
            throw new \RuntimeException('Could not create rules directory: ' . $rulesDir);
        }
    }

    /**
     * @param array<string, array<int, ParsedRule>> $rulesBySourceFile
     * @param array<int, string> $warnings
     * @return array{rule_count: int, file_count: int, warnings: int}
     */
    public function write(array $rulesBySourceFile, string $crsVersion, array $warnings): array
    {
        $this->clearExisting();

        $manifestFiles = [];
        $allRules = [];
        $totalRules = 0;

        ksort($rulesBySourceFile);
        foreach ($rulesBySourceFile as $sourceFile => $rules) {
            $jsonName = $this->jsonNameFor($sourceFile);
            $rulesArray = [];
            foreach ($rules as $rule) {
                $rulesArray[] = $rule->toArray();
                $allRules[] = $rule->toArray();
            }

            $payload = [
                'source_file'  => $sourceFile,
                'crs_version'  => $crsVersion,
                'rule_count'   => count($rulesArray),
                'rules'        => $rulesArray,
            ];
            file_put_contents(
                $this->rulesDir . '/' . $jsonName,
                json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n"
            );
            $manifestFiles[] = $jsonName;
            $totalRules += count($rulesArray);
        }

        $manifest = [
            'version'      => $crsVersion,
            'generated_at' => gmdate('c'),
            'rule_count'   => $totalRules,
            'files'        => $manifestFiles,
            'warnings'     => $warnings,
        ];
        file_put_contents(
            $this->rulesDir . '/manifest.json',
            json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n"
        );

        $compiled = [
            'version' => $crsVersion,
            'rules'   => $allRules,
        ];
        file_put_contents(
            $this->rulesDir . '/compiled.php',
            "<?php\n// Auto-generated by bin/refresh-crs. Do not edit by hand.\nreturn " . var_export($compiled, true) . ";\n"
        );

        return [
            'rule_count' => $totalRules,
            'file_count' => count($manifestFiles),
            'warnings'   => count($warnings),
        ];
    }

    private function clearExisting(): void
    {
        foreach (glob($this->rulesDir . '/*.json') ?: [] as $f) {
            unlink($f);
        }

        $compiled = $this->rulesDir . '/compiled.php';
        if (is_file($compiled)) {
            unlink($compiled);
        }
    }

    private function jsonNameFor(string $sourceFile): string
    {
        return preg_replace('/\.conf$/', '.json', basename($sourceFile)) ?: ($sourceFile . '.json');
    }
}
