<?php

declare(strict_types=1);

namespace Kanopi\Crs\Refresh;

use Kanopi\Crs\Parser\ParsedRule;

/**
 * Writes parsed CRS rules to the engine's on-disk cache:
 *   rules/manifest.json       — version + file index
 *   rules/<source>.json       — per-source-file rule array (review-friendly)
 *   rules/compiled.php        — single var_export'd array (runtime hot path)
 */
final class RuleWriter
{
    public function __construct(private readonly string $rulesDir)
    {
        if (!is_dir($rulesDir) && !@mkdir($rulesDir, 0755, true) && !is_dir($rulesDir)) {
            throw new \RuntimeException('Could not create rules directory: ' . $rulesDir);
        }
    }

    /**
     * @param array<string, array<int, ParsedRule>> $rulesBySourceFile
     * @param array<int, string> $warnings
     * @return array{rule_count: int, file_count: int, warnings: int}
     */
    public function write(array $rulesBySourceFile, string $crsVersion, array $warnings): array
    {
        // Everything is built in a staging directory and swapped in only once
        // it is complete. Writing in place meant a failure part-way through —
        // disk full, permissions, a throw between files — left rules/ with no
        // compiled.php and an arbitrary subset of the JSON, which
        // RuleSet::loadFromDirectory() would then happily load as if it were
        // the whole ruleset.
        $staging = $this->rulesDir . '.staging-' . getmypid();
        $this->removeDirectory($staging);
        if (!@mkdir($staging, 0755, true) && !is_dir($staging)) {
            throw new \RuntimeException('Could not create staging directory: ' . $staging);
        }

        try {
            $stats = $this->buildInto($staging, $rulesBySourceFile, $crsVersion, $warnings);
            $this->swapIntoPlace($staging);
        } catch (\Throwable $throwable) {
            $this->removeDirectory($staging);
            throw $throwable;
        }

        return $stats;
    }

    /**
     * @param array<string, array<int, ParsedRule>> $rulesBySourceFile
     * @param array<int, string> $warnings
     * @return array{rule_count: int, file_count: int, warnings: int}
     */
    private function buildInto(string $targetDir, array $rulesBySourceFile, string $crsVersion, array $warnings): array
    {
        $manifestFiles = [];
        $allRules = [];
        $totalRules = 0;

        ksort($rulesBySourceFile);
        foreach ($rulesBySourceFile as $sourceFile => $rules) {
            $jsonName = $this->jsonNameFor($sourceFile);
            $rulesArray = [];
            foreach ($rules as $rule) {
                $rulesArray[] = $rule->toArray();
                $allRules[] = $rule->toArray();
            }

            $payload = [
                'source_file'  => $sourceFile,
                'crs_version'  => $crsVersion,
                'rule_count'   => count($rulesArray),
                'rules'        => $rulesArray,
            ];
            $this->put(
                $targetDir . '/' . $jsonName,
                json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n"
            );
            $manifestFiles[] = $jsonName;
            $totalRules += count($rulesArray);
        }

        $manifest = [
            'version'      => $crsVersion,
            'generated_at' => gmdate('c'),
            'rule_count'   => $totalRules,
            'files'        => $manifestFiles,
            'warnings'     => $warnings,
        ];
        $this->put(
            $targetDir . '/manifest.json',
            json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n"
        );

        $compiled = [
            'version' => $crsVersion,
            'rules'   => $allRules,
        ];
        $this->put(
            $targetDir . '/compiled.php',
            "<?php\n// Auto-generated by bin/refresh-crs. Do not edit by hand.\nreturn " . var_export($compiled, true) . ";\n"
        );

        return [
            'rule_count' => $totalRules,
            'file_count' => count($manifestFiles),
            'warnings'   => count($warnings),
        ];
    }

    /**
     * An unchecked file_put_contents() reports a healthy rule_count while
     * having written nothing, so a short or failed write has to be an error.
     */
    private function put(string $path, string $contents): void
    {
        $written = file_put_contents($path, $contents);
        if ($written === false || $written !== strlen($contents)) {
            throw new \RuntimeException('Failed to write ' . $path);
        }
    }

    /**
     * Swap staging in for the live directory. The old directory is moved
     * aside rather than deleted, so a failed swap can be rolled back and the
     * previous ruleset survives.
     */
    private function swapIntoPlace(string $staging): void
    {
        $backup = $this->rulesDir . '.backup-' . getmypid();
        $this->removeDirectory($backup);

        $hadPrevious = is_dir($this->rulesDir);
        if ($hadPrevious && !@rename($this->rulesDir, $backup)) {
            throw new \RuntimeException('Could not move the existing ruleset aside: ' . $this->rulesDir);
        }

        if (!@rename($staging, $this->rulesDir)) {
            if ($hadPrevious) {
                @rename($backup, $this->rulesDir);
            }

            throw new \RuntimeException('Could not move the new ruleset into place: ' . $this->rulesDir);
        }

        $this->removeDirectory($backup);
    }

    private function removeDirectory(string $dir): void
    {
        if (!is_dir($dir)) {
            return;
        }

        foreach (glob($dir . '/*') ?: [] as $entry) {
            if (is_dir($entry)) {
                $this->removeDirectory($entry);
                continue;
            }

            unlink($entry);
        }

        rmdir($dir);
    }

    private function jsonNameFor(string $sourceFile): string
    {
        return preg_replace('/\.conf$/', '.json', basename($sourceFile)) ?: ($sourceFile . '.json');
    }
}
