<?php

declare(strict_types=1);

namespace Kanopi\Crs\Refresh;

use Kanopi\Crs\Parser\ParsedRule;

/**
 * Writes parsed CRS rules to the engine's on-disk cache:
 *   rules/manifest.json       — version + file index
 *   rules/<source>.json       — per-source-file rule array (review-friendly)
 *   rules/compiled.php        — single var_export'd array (runtime hot path)
 */
final class RuleWriter
{
    /**
     * The only file the runtime reads when it is present — see
     * RuleSet::loadFromDirectory(). Everything else in rules/ is a review
     * artifact, which is what makes an atomic swap achievable: replacing one
     * file with rename() is a single atomic operation, replacing a directory
     * is not.
     */
    private const COMPILED = 'compiled.php';

    public function __construct(private readonly string $rulesDir)
    {
        if (!is_dir($rulesDir) && !@mkdir($rulesDir, 0755, true) && !is_dir($rulesDir)) {
            throw new \RuntimeException('Could not create rules directory: ' . $rulesDir);
        }
    }

    /**
     * @param array<string, array<int, ParsedRule>> $rulesBySourceFile
     * @param array<int, string> $warnings
     * @return array{rule_count: int, file_count: int, warnings: int}
     */
    public function write(array $rulesBySourceFile, string $crsVersion, array $warnings): array
    {
        // Everything is built in a staging directory and swapped in only once
        // it is complete. Writing in place meant a failure part-way through —
        // disk full, permissions, a throw between files — left rules/ with no
        // compiled.php and an arbitrary subset of the JSON, which
        // RuleSet::loadFromDirectory() would then happily load as if it were
        // the whole ruleset.
        $staging = $this->rulesDir . '.staging-' . getmypid();
        $this->removeDirectory($staging);
        if (!@mkdir($staging, 0755, true) && !is_dir($staging)) {
            throw new \RuntimeException('Could not create staging directory: ' . $staging);
        }

        try {
            $stats = $this->buildInto($staging, $rulesBySourceFile, $crsVersion, $warnings);
            $this->swapIntoPlace($staging);
        } catch (\Throwable $throwable) {
            $this->removeDirectory($staging);
            throw $throwable;
        }

        // swapIntoPlace() moves files out of staging one at a time rather than
        // renaming the directory wholesale, so the empty shell is still here and
        // has to be cleared explicitly. Left behind, the next run finds it
        // already present, skips past its own mkdir guard, and builds into a
        // directory it did not create.
        $this->removeDirectory($staging);

        return $stats;
    }

    /**
     * @param array<string, array<int, ParsedRule>> $rulesBySourceFile
     * @param array<int, string> $warnings
     * @return array{rule_count: int, file_count: int, warnings: int}
     */
    private function buildInto(string $targetDir, array $rulesBySourceFile, string $crsVersion, array $warnings): array
    {
        $manifestFiles = [];
        $allRules = [];
        $totalRules = 0;

        ksort($rulesBySourceFile);
        foreach ($rulesBySourceFile as $sourceFile => $rules) {
            $jsonName = $this->jsonNameFor($sourceFile);
            $rulesArray = [];
            foreach ($rules as $rule) {
                $rulesArray[] = $rule->toArray();
                $allRules[] = $rule->toArray();
            }

            $payload = [
                'source_file'  => $sourceFile,
                'crs_version'  => $crsVersion,
                'rule_count'   => count($rulesArray),
                'rules'        => $rulesArray,
            ];
            $this->put(
                $targetDir . '/' . $jsonName,
                json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n"
            );
            $manifestFiles[] = $jsonName;
            $totalRules += count($rulesArray);
        }

        $manifest = [
            'version'      => $crsVersion,
            'generated_at' => gmdate('c'),
            'rule_count'   => $totalRules,
            'files'        => $manifestFiles,
            'warnings'     => $warnings,
        ];
        $this->put(
            $targetDir . '/manifest.json',
            json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n"
        );

        $compiled = [
            'version' => $crsVersion,
            'rules'   => $allRules,
        ];
        $this->put(
            $targetDir . '/compiled.php',
            "<?php\n// Auto-generated by bin/refresh-crs. Do not edit by hand.\nreturn " . var_export($compiled, true) . ";\n"
        );

        return [
            'rule_count' => $totalRules,
            'file_count' => count($manifestFiles),
            'warnings'   => count($warnings),
        ];
    }

    /**
     * An unchecked file_put_contents() reports a healthy rule_count while
     * having written nothing, so a short or failed write has to be an error.
     */
    private function put(string $path, string $contents): void
    {
        $written = file_put_contents($path, $contents);
        if ($written === false || $written !== strlen($contents)) {
            throw new \RuntimeException('Failed to write ' . $path);
        }
    }

    /**
     * Swap staging in for the live ruleset without rules/ ever being absent.
     *
     * The previous implementation renamed rules/ aside and then renamed staging
     * into its place. Two renames means a window — short, but a real one — in
     * which rules/ does not exist, and a worker calling
     * RuleSet::loadFromDirectory() during it got a hard ConfigurationException
     * rather than a stale-but-valid ruleset. A directory cannot be replaced
     * atomically; rename() over an existing *file* can be.
     *
     * So the order is inverted. rules/ stays where it is, the review artifacts
     * are moved in first, and compiled.php — the only file the runtime reads —
     * goes last in a single rename(). A reader therefore sees either the whole
     * old ruleset or the whole new one, and never nothing.
     *
     * A copy of the previous contents is kept until the swap completes so a
     * failure part-way through can be undone. It is a copy rather than a
     * rename precisely because rules/ has to stay readable throughout.
     */
    private function swapIntoPlace(string $staging): void
    {
        if (!is_dir($this->rulesDir) && !@mkdir($this->rulesDir, 0755, true) && !is_dir($this->rulesDir)) {
            throw new \RuntimeException('Could not create rules directory: ' . $this->rulesDir);
        }

        $backup = $this->rulesDir . '.backup-' . getmypid();
        $this->removeDirectory($backup);
        $this->copyDirectory($this->rulesDir, $backup);

        try {
            $staged = [];
            foreach (glob($staging . '/*') ?: [] as $file) {
                $staged[basename($file)] = $file;
            }

            // Artifacts first. Each rename() is atomic on its own, and none of
            // them is what the runtime loads, so a reader during this stretch
            // still gets the old compiled.php in full.
            foreach ($staged as $name => $file) {
                if ($name === self::COMPILED) {
                    continue;
                }

                if (!@rename($file, $this->rulesDir . '/' . $name)) {
                    throw new \RuntimeException('Could not move ' . $name . ' into ' . $this->rulesDir);
                }
            }

            // Anything the new ruleset no longer has — a CRS release that
            // dropped a rule file. Removed before the flip so the new
            // compiled.php never coexists with artifacts it does not describe.
            foreach (glob($this->rulesDir . '/*') ?: [] as $existing) {
                $name = basename($existing);
                if ($name === self::COMPILED) {
                    continue;
                }

                if (isset($staged[$name])) {
                    continue;
                }

                if (is_dir($existing)) {
                    $this->removeDirectory($existing);
                    continue;
                }

                @unlink($existing);
            }

            // The flip.
            if (isset($staged[self::COMPILED]) && !@rename($staged[self::COMPILED], $this->rulesDir . '/' . self::COMPILED)) {
                throw new \RuntimeException('Could not move the compiled ruleset into place: ' . $this->rulesDir);
            }
        } catch (\Throwable $throwable) {
            $this->restoreFrom($backup);
            throw $throwable;
        }

        $this->removeDirectory($backup);
    }

    /**
     * Put the previous contents back after a failed swap. compiled.php is
     * restored last for the same reason it is written last.
     */
    private function restoreFrom(string $backup): void
    {
        if (!is_dir($backup)) {
            return;
        }

        foreach (glob($this->rulesDir . '/*') ?: [] as $existing) {
            if (basename($existing) === self::COMPILED) {
                continue;
            }

            if (is_dir($existing)) {
                $this->removeDirectory($existing);
                continue;
            }

            @unlink($existing);
        }

        $compiled = null;
        foreach (glob($backup . '/*') ?: [] as $file) {
            if (basename($file) === self::COMPILED) {
                $compiled = $file;
                continue;
            }

            @copy($file, $this->rulesDir . '/' . basename($file));
        }

        if ($compiled !== null) {
            @copy($compiled, $this->rulesDir . '/' . self::COMPILED);
        }
    }

    private function copyDirectory(string $from, string $to): void
    {
        if (!is_dir($to) && !@mkdir($to, 0755, true) && !is_dir($to)) {
            throw new \RuntimeException('Could not create backup directory: ' . $to);
        }

        foreach (glob($from . '/*') ?: [] as $file) {
            if (is_dir($file)) {
                $this->copyDirectory($file, $to . '/' . basename($file));
                continue;
            }

            if (!@copy($file, $to . '/' . basename($file))) {
                throw new \RuntimeException('Could not back up ' . $file);
            }
        }
    }

    private function removeDirectory(string $dir): void
    {
        if (!is_dir($dir)) {
            return;
        }

        foreach (glob($dir . '/*') ?: [] as $entry) {
            if (is_dir($entry)) {
                $this->removeDirectory($entry);
                continue;
            }

            unlink($entry);
        }

        rmdir($dir);
    }

    private function jsonNameFor(string $sourceFile): string
    {
        return preg_replace('/\.conf$/', '.json', basename($sourceFile)) ?: ($sourceFile . '.json');
    }
}
